version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile

    container_name: php-halado-vizsgamunka
    restart: always
    working_dir: /var/www
    volumes:
      - ../src:/var/www
      - ./nginx/php.ini/:/usr/local/etc/php/conf.d/php.ini

  nginx:
    image: nginx:1.19-alpine
    container_name: php-halado-vizsgamunka-nginx
    restart: always
    ports:
      - '8000:80'
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d

  db:
    container_name: php-halado-vizsgamunka-db
    image: mysql:8.0
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
